### ISSUE TITLE
Different Language Models

### ISSUE THREAD

**Issue by appatalks** [appatalks/chatgpt-html#14]
May add competing engines to the options when a bit more matured.

Currently on the radar (in order of what looks best so far):

oobabooga: https://github.com/oobabooga/text-generation-webui
 -- https://huggingface.co/mosaicml/mpt-7b-storywriter
StableVicuna: https://stability.ai/blog/stablevicuna-open-source-rlhf-chatbot
StableLM - https://stability.ai/blog/stability-ai-launches-the-first-of-its-stablelm-suite-of-language-models
Dolly by Databricks: https://www.databricks.com/blog/2023/04/12/dolly-first-open-commercially-viable-instruction-tuned-llm
Alpaca - Stanford Univ: https://crfm.stanford.edu/2023/03/13/alpaca.html
Whisper Text-to-Speech: https://github.com/openai/whisper#available-models-and-languages
Meta LLaMA: https://github.com/facebookresearch/llama 

Added to code base:
Bark Text-to-speech: https://github.com/suno-ai/bark (Seriously kool stuff here!) **Added May1st2023**
Google Bard: https://blog.google/technology/ai/bard-google-ai-search-updates/ 
MakerSuite and PalmAPI: https://makersuite.google.com/waitlist

**Comment by servingbaby** [comment]
https://github.com/openai/whisper#available-models-and-languages

**Comment by appatalks** [comment]
Quick add API key ref:
```
<textarea id="apiKeyinput" rows="1" wrap="soft" style="width: 125px; margin-left: 3px; margin-top: 2px" placeholder="API_KEY">


    var sQAPI = apiKeyinput.value;
    if (sQAPI == "") {
        alert("Enter your API Key!");
        apiKeyinput.focus();
        return;
    }

    var API_KEY = document.getElementById("apiKeyinput").value;
    
```

**Comment by servingbaby** [comment]
Dolly by Databricks : https://www.databricks.com/blog/2023/04/12/dolly-first-open-commercially-viable-instruction-tuned-llm

Alpaca - Stanford Univ. : https://crfm.stanford.edu/2023/03/13/alpaca.html

**Comment by appatalks** [comment]
Good Reading:
https://blog.google/technology/ai/google-palm-2-ai-large-language-model/
https://ai.google/static/documents/palm2techreport.pdf

**Comment by appatalks** [comment]
Happy with OpenAI and Google PaLM for now. 
Will reopen when a leap in the overall technology matures.
