### ISSUE TITLE
3.5-turbo API Call structure

### ISSUE THREAD

**Issue by appatalks** [appatalks/chatgpt-html#16]
With "gpt-3.5-turbo", need to relook at structure for proper implementation. 

Ex:
[
  {“role”: “system”, “content”: “You are a helpful assistant that translates English to French.”},
  {“role”: “user”, “content”: ‘Translate the following English text to French: “{text}”’}
]

Currently just using user and content line to pass. (easiest to get working after release of gpt-3.5-turbo)

https://platform.openai.com/docs/guides/chat/chat-vs-completions

**Comment by servingbaby** [comment]
Need to add for error detection:

{
    "error": {
        "message": "Rate limit reached for default-gpt-3.5-turbo in organization org-giRW9Hp53PN1qnWQMAZiv31g on requests per min. Limit: 20 / min. Current: 30 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.",
        "type": "requests",
        "param": null,
        "code": null
    }
}

**Comment by appatalks** [comment]
"In general, gpt-3.5-turbo-0301 does not pay strong attention to the system message, and therefore important instructions are often better placed in a user message."

This seems pretty obvious now :/

**Comment by appatalks** [comment]
I couldn't (yet) figure out how to pass an array that is actively updated to messages when user/bot interaction happens.
So, atm I am passing all the history back, but having assistant content mention to know its all part of the previous chat. Seems to work'ish.

    messages: [
	      { role: 'system', content: "You are Eva. You have access to previous chats and responses. You will keep conversation to a minimum and answer to the best of your abilities." },  // Doesn't seem to stick well.
	      { role: 'user', content: selPers.value + "My next question is: " + sQuestion.replace(/\n/g, '') }, 
          { role: 'assistant', content: "Here are all my previous responses for you to remember: " + userMasterResponse.replace(/\n/g, ' ') }, 
	],

**Comment by appatalks** [comment]
Pretty happy with this or a variation of it:

	messages: [
	      { role: 'system', content: "You are Eva. You have access to previous chats and responses. You will keep conversation to a minimum and answer to the best of your abilities." }, 
	      { role: 'user', content: selPers.value }, 
          { role: 'assistant', content: "Here are all my previous responses for you to remember: " + userMasterResponse.replace(/\n/g, ' ') }, 
	      { role: 'user', content: "My next response is: " + sQuestion.replace(/\n/g, '') }, 
	],

**Comment by appatalks** [comment]
Reopening. I feel I am close to getting this into an active array:


///
    // Set initial Messages payload
    let iMessages = [
      { role: 'system', content: "You are Eva. You have access to previous chats and responses. You will keep conversation to a minimum and answer to the best of your abilities." },
      { role: 'user', content: selPers.value },
//      { role: 'assistant', content: "Here are all my previous responses for you to remember: " + userMasterResponse.replace(/\n/g, ' ') }, 
//      { role: 'user', content: "My next response is: " + sQuestion.replace(/\n/g, '') }, 
    ];

    // Store messages in local storage
    // localStorage.setItem("messages", JSON.stringify(iMessages));

    // Retrieve messages from local storage
    var cStoredMessages = localStorage.getItem("messages");
    // kMessages = cStoredMessages ? JSON.parse(cStoredMessages) : [];
    kMessages = iMessages + cStoredMessages ? JSON.parse(cStoredMessages) : [];

   // Append last responses to next payload
       // Placer
iMessages.push({ role: 'assistant', content: "Here are all my previous responses for you to remember: " + userMasterResponse.replace(/\n/g, ' ') });
iMessages.push({ role: 'user', content: "My next response is: " + sQuestion.replace(/\n/g, '') });


// Store the updated messages array back to local storage
localStorage.setItem("messages", JSON.stringify(iMessages));
///

    // API Payload
    var data = {
        model: sModel,
        messages: kMessages,
        max_tokens: iMaxTokens,
        temperature:  dTemperature,
        frequency_penalty: eFrequency_penalty,
        presence_penalty: cPresence_penalty,
        stop: hStop
    }

**Comment by appatalks** [comment]
Woot Woot got memeory down. Per community, next goal:



[ruby_coder](https://community.openai.com/u/ruby_coder)
Regular
(https://community.openai.com/t/gpt-3-5-turbo-vs-text-davinci-003-chatbot/82806/73?u=sbennettkorea)
Very happy atm.
Good for you, [@sbennettkorea](https://community.openai.com/u/sbennettkorea)
It’s great to hear you are enjoying coding.
Next, you can work on code to prune the messages array when it gets too large.

**Comment by appatalks** [comment]
Added a Clear Memory button for the time being. I'll revisit this.

**Comment by appatalks** [comment]
You know what, I am happy with this. Ill prolly reopen this if I ever run into a limits issue.
